# Generated by Django 4.2.5 on 2024-01-31 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_usermaster_otp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='usermaster',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
