# Generated by Django 4.2.5 on 2024-01-31 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_user_id_candidate_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='user',
            new_name='user_id',
        ),
    ]
