# Generated by Django 4.2.5 on 2024-02-04 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_jobdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetails',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.usermaster'),
            preserve_default=False,
        ),
    ]
