# Generated by Django 4.2.5 on 2024-02-07 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_jobdetails_company_website_jobdetails_company_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobdetails',
            old_name='Company_website',
            new_name='company_website',
        ),
    ]
