# Generated by Django 4.2.5 on 2024-02-07 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_rename_company_website_jobdetails_company_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdetails',
            name='company_logo',
            field=models.ImageField(upload_to='img/company/jobpost'),
        ),
    ]
