# Generated by Django 4.2.5 on 2024-02-08 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_jobdetails_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetails',
            name='vacancy',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
