# Generated by Django 4.2.5 on 2024-02-08 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_jobdetails_vacancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetails',
            name='application_deadline',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobdetails',
            name='gender',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobdetails',
            name='published_date',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
