# Generated by Django 4.2.5 on 2024-02-09 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_jobdetails_application_deadline_jobdetails_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education', models.CharField(max_length=250)),
                ('portfoliowebsite', models.CharField(max_length=250)),
                ('minimumsalary', models.CharField(max_length=250)),
                ('maximumsalary', models.CharField(max_length=250)),
                ('resume', models.FileField(upload_to='app/resume')),
                ('candidate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usermaster')),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.jobdetails')),
            ],
        ),
    ]
