# Generated by Django 4.2.5 on 2024-02-09 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_applylist'),
    ]

    operations = [
        migrations.AddField(
            model_name='applylist',
            name='experience',
            field=models.IntegerField(default=2),
        ),
    ]
