# Generated by Django 4.2.5 on 2024-02-14 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_applylist_experience'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermaster',
            old_name='is_verifird',
            new_name='is_verify',
        ),
        migrations.AlterField(
            model_name='applylist',
            name='candidate_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.candidate'),
        ),
    ]
