# Generated by Django 5.0.1 on 2024-03-29 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_rename_is_verifird_usermaster_is_verify_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermaster',
            name='is_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
