# Generated by Django 5.0.1 on 2024-03-29 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_usermaster_is_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermaster',
            name='is_updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
