# Generated by Django 5.0.1 on 2024-03-31 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_usermaster_is_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdetails',
            name='jobdescription',
            field=models.CharField(max_length=500),
        ),
    ]
