# Generated by Django 5.0.1 on 2024-03-31 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_jobdetails_jobdescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdetails',
            name='jobdescription',
            field=models.CharField(max_length=800),
        ),
    ]
